# version: "3.8"

# services:
#   postgres:
#     image: postgres:15
#     container_name: wallet-db
#     restart: always
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#       - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

#   app:
#     build: .
#     container_name: wallet-api
#     restart: always
#     depends_on:
#       - postgres
#     ports:
#       - "4000:4000"
#     environment:
#       DATABASE_URL: ${DATABASE_URL}
#       JWT_SECRET: ${JWT_SECRET}

# volumes:
#   pgdata:


version: "3.8"

services:
  app:
    build: .
    container_name: wallet-api
    
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env          # <-- THIS LINE IS CRUCIAL
    environment:
      DATABASE_URL: ${SUPABASE_DB_URL}
      JWT_SECRET: ${JWT_SECRET}
